# this workflow sends an alert to the project discord server on pushes and PRs on the develop branch

name: Send an alert to discord

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

permissions:
  contents: read

jobs:
  alert:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        fetch-depth: 0
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install discord==2.0.0
        pip install discord.py==2.0.1

    - name: Send Message Over Discord...
      env:
        DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN}}
        SERVER_ID: ${{ secrets.SERVER_ID}}
        TEXT: push to develop by ${{ github.actor }}
      run: |
        python deployment/discordbot.py
        
